# Generated by Django 4.0 on 2022-08-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
    ]
