# Generated by Django 4.0 on 2022-08-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_national_no'),
        ('deposit', '0002_alter_deposit_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer.customer'),
        ),
    ]
