# Generated by Django 4.0 on 2022-08-07 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_national_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_no',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_national_number', message='National number must be numeric and 10 digits', regex='^[1-9][0-9]{9}*$')], verbose_name='National number'),
        ),
    ]
